//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 Copyright 2023 The Kapacity Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapPortraitAlgorithmResultSource) DeepCopyInto(out *ConfigMapPortraitAlgorithmResultSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapPortraitAlgorithmResultSource.
func (in *ConfigMapPortraitAlgorithmResultSource) DeepCopy() *ConfigMapPortraitAlgorithmResultSource {
	if in == nil {
		return nil
	}
	out := new(ConfigMapPortraitAlgorithmResultSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronHorizontalPortraitData) DeepCopyInto(out *CronHorizontalPortraitData) {
	*out = *in
	if in.Crons != nil {
		in, out := &in.Crons, &out.Crons
		*out = make([]ReplicaCron, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronHorizontalPortraitData.
func (in *CronHorizontalPortraitData) DeepCopy() *CronHorizontalPortraitData {
	if in == nil {
		return nil
	}
	out := new(CronHorizontalPortraitData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronHorizontalPortraitProvider) DeepCopyInto(out *CronHorizontalPortraitProvider) {
	*out = *in
	if in.Crons != nil {
		in, out := &in.Crons, &out.Crons
		*out = make([]ReplicaCron, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronHorizontalPortraitProvider.
func (in *CronHorizontalPortraitProvider) DeepCopy() *CronHorizontalPortraitProvider {
	if in == nil {
		return nil
	}
	out := new(CronHorizontalPortraitProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobPortraitAlgorithmJob) DeepCopyInto(out *CronJobPortraitAlgorithmJob) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobPortraitAlgorithmJob.
func (in *CronJobPortraitAlgorithmJob) DeepCopy() *CronJobPortraitAlgorithmJob {
	if in == nil {
		return nil
	}
	out := new(CronJobPortraitAlgorithmJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobTemplateSpec) DeepCopyInto(out *CronJobTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobTemplateSpec.
func (in *CronJobTemplateSpec) DeepCopy() *CronJobTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CronJobTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicHorizontalPortraitProvider) DeepCopyInto(out *DynamicHorizontalPortraitProvider) {
	*out = *in
	in.PortraitSpec.DeepCopyInto(&out.PortraitSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicHorizontalPortraitProvider.
func (in *DynamicHorizontalPortraitProvider) DeepCopy() *DynamicHorizontalPortraitProvider {
	if in == nil {
		return nil
	}
	out := new(DynamicHorizontalPortraitProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalJobPortraitAlgorithm) DeepCopyInto(out *ExternalJobPortraitAlgorithm) {
	*out = *in
	in.Job.DeepCopyInto(&out.Job)
	in.ResultSource.DeepCopyInto(&out.ResultSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalJobPortraitAlgorithm.
func (in *ExternalJobPortraitAlgorithm) DeepCopy() *ExternalJobPortraitAlgorithm {
	if in == nil {
		return nil
	}
	out := new(ExternalJobPortraitAlgorithm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPodSorter) DeepCopyInto(out *ExternalPodSorter) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPodSorter.
func (in *ExternalPodSorter) DeepCopy() *ExternalPodSorter {
	if in == nil {
		return nil
	}
	out := new(ExternalPodSorter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPodTrafficController) DeepCopyInto(out *ExternalPodTrafficController) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPodTrafficController.
func (in *ExternalPodTrafficController) DeepCopy() *ExternalPodTrafficController {
	if in == nil {
		return nil
	}
	out := new(ExternalPodTrafficController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalStabilityChecker) DeepCopyInto(out *ExternalStabilityChecker) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalStabilityChecker.
func (in *ExternalStabilityChecker) DeepCopy() *ExternalStabilityChecker {
	if in == nil {
		return nil
	}
	out := new(ExternalStabilityChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrayStatus) DeepCopyInto(out *GrayStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrayStatus.
func (in *GrayStatus) DeepCopy() *GrayStatus {
	if in == nil {
		return nil
	}
	out := new(GrayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrayStrategy) DeepCopyInto(out *GrayStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrayStrategy.
func (in *GrayStrategy) DeepCopy() *GrayStrategy {
	if in == nil {
		return nil
	}
	out := new(GrayStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortrait) DeepCopyInto(out *HorizontalPortrait) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortrait.
func (in *HorizontalPortrait) DeepCopy() *HorizontalPortrait {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortrait)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorizontalPortrait) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortraitData) DeepCopyInto(out *HorizontalPortraitData) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticHorizontalPortraitData)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(CronHorizontalPortraitData)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeSeries != nil {
		in, out := &in.TimeSeries, &out.TimeSeries
		*out = new(TimeSeriesHorizontalPortraitData)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpireTime != nil {
		in, out := &in.ExpireTime, &out.ExpireTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortraitData.
func (in *HorizontalPortraitData) DeepCopy() *HorizontalPortraitData {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortraitData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortraitList) DeepCopyInto(out *HorizontalPortraitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HorizontalPortrait, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortraitList.
func (in *HorizontalPortraitList) DeepCopy() *HorizontalPortraitList {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortraitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorizontalPortraitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortraitProvider) DeepCopyInto(out *HorizontalPortraitProvider) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticHorizontalPortraitProvider)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(CronHorizontalPortraitProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Dynamic != nil {
		in, out := &in.Dynamic, &out.Dynamic
		*out = new(DynamicHorizontalPortraitProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortraitProvider.
func (in *HorizontalPortraitProvider) DeepCopy() *HorizontalPortraitProvider {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortraitProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortraitSpec) DeepCopyInto(out *HorizontalPortraitSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	in.PortraitSpec.DeepCopyInto(&out.PortraitSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortraitSpec.
func (in *HorizontalPortraitSpec) DeepCopy() *HorizontalPortraitSpec {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortraitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortraitStatus) DeepCopyInto(out *HorizontalPortraitStatus) {
	*out = *in
	if in.PortraitData != nil {
		in, out := &in.PortraitData, &out.PortraitData
		*out = new(HorizontalPortraitData)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortraitStatus.
func (in *HorizontalPortraitStatus) DeepCopy() *HorizontalPortraitStatus {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortraitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPortraitValue) DeepCopyInto(out *HorizontalPortraitValue) {
	*out = *in
	if in.ExpireTime != nil {
		in, out := &in.ExpireTime, &out.ExpireTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPortraitValue.
func (in *HorizontalPortraitValue) DeepCopy() *HorizontalPortraitValue {
	if in == nil {
		return nil
	}
	out := new(HorizontalPortraitValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentHorizontalPodAutoscaler) DeepCopyInto(out *IntelligentHorizontalPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentHorizontalPodAutoscaler.
func (in *IntelligentHorizontalPodAutoscaler) DeepCopy() *IntelligentHorizontalPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(IntelligentHorizontalPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntelligentHorizontalPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentHorizontalPodAutoscalerBehavior) DeepCopyInto(out *IntelligentHorizontalPodAutoscalerBehavior) {
	*out = *in
	in.ScaleUp.DeepCopyInto(&out.ScaleUp)
	in.ScaleDown.DeepCopyInto(&out.ScaleDown)
	if in.ReplicaProfile != nil {
		in, out := &in.ReplicaProfile, &out.ReplicaProfile
		*out = new(ReplicaProfileBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentHorizontalPodAutoscalerBehavior.
func (in *IntelligentHorizontalPodAutoscalerBehavior) DeepCopy() *IntelligentHorizontalPodAutoscalerBehavior {
	if in == nil {
		return nil
	}
	out := new(IntelligentHorizontalPodAutoscalerBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentHorizontalPodAutoscalerList) DeepCopyInto(out *IntelligentHorizontalPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntelligentHorizontalPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentHorizontalPodAutoscalerList.
func (in *IntelligentHorizontalPodAutoscalerList) DeepCopy() *IntelligentHorizontalPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(IntelligentHorizontalPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntelligentHorizontalPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentHorizontalPodAutoscalerSpec) DeepCopyInto(out *IntelligentHorizontalPodAutoscalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.PortraitProviders != nil {
		in, out := &in.PortraitProviders, &out.PortraitProviders
		*out = make([]HorizontalPortraitProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Behavior.DeepCopyInto(&out.Behavior)
	if in.StabilityCheckers != nil {
		in, out := &in.StabilityCheckers, &out.StabilityCheckers
		*out = make([]StabilityChecker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentHorizontalPodAutoscalerSpec.
func (in *IntelligentHorizontalPodAutoscalerSpec) DeepCopy() *IntelligentHorizontalPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(IntelligentHorizontalPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentHorizontalPodAutoscalerStatus) DeepCopyInto(out *IntelligentHorizontalPodAutoscalerStatus) {
	*out = *in
	if in.PreviousPortraitValue != nil {
		in, out := &in.PreviousPortraitValue, &out.PreviousPortraitValue
		*out = new(HorizontalPortraitValue)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentPortraitValue != nil {
		in, out := &in.CurrentPortraitValue, &out.CurrentPortraitValue
		*out = new(HorizontalPortraitValue)
		(*in).DeepCopyInto(*out)
	}
	if in.Gray != nil {
		in, out := &in.Gray, &out.Gray
		*out = new(GrayStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentHorizontalPodAutoscalerStatus.
func (in *IntelligentHorizontalPodAutoscalerStatus) DeepCopy() *IntelligentHorizontalPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(IntelligentHorizontalPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeHPAPortraitAlgorithm) DeepCopyInto(out *KubeHPAPortraitAlgorithm) {
	*out = *in
	out.SyncPeriod = in.SyncPeriod
	out.CPUInitializationPeriod = in.CPUInitializationPeriod
	out.InitialReadinessDelay = in.InitialReadinessDelay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeHPAPortraitAlgorithm.
func (in *KubeHPAPortraitAlgorithm) DeepCopy() *KubeHPAPortraitAlgorithm {
	if in == nil {
		return nil
	}
	out := new(KubeHPAPortraitAlgorithm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	in.MetricSpec.DeepCopyInto(&out.MetricSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpec.
func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsStabilityChecker) DeepCopyInto(out *MetricsStabilityChecker) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsStabilityChecker.
func (in *MetricsStabilityChecker) DeepCopy() *MetricsStabilityChecker {
	if in == nil {
		return nil
	}
	out := new(MetricsStabilityChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSorter) DeepCopyInto(out *PodSorter) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalPodSorter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSorter.
func (in *PodSorter) DeepCopy() *PodSorter {
	if in == nil {
		return nil
	}
	out := new(PodSorter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTrafficController) DeepCopyInto(out *PodTrafficController) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalPodTrafficController)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTrafficController.
func (in *PodTrafficController) DeepCopy() *PodTrafficController {
	if in == nil {
		return nil
	}
	out := new(PodTrafficController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortraitAlgorithm) DeepCopyInto(out *PortraitAlgorithm) {
	*out = *in
	if in.ExternalJob != nil {
		in, out := &in.ExternalJob, &out.ExternalJob
		*out = new(ExternalJobPortraitAlgorithm)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeHPA != nil {
		in, out := &in.KubeHPA, &out.KubeHPA
		*out = new(KubeHPAPortraitAlgorithm)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortraitAlgorithm.
func (in *PortraitAlgorithm) DeepCopy() *PortraitAlgorithm {
	if in == nil {
		return nil
	}
	out := new(PortraitAlgorithm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortraitAlgorithmJob) DeepCopyInto(out *PortraitAlgorithmJob) {
	*out = *in
	if in.CronJob != nil {
		in, out := &in.CronJob, &out.CronJob
		*out = new(CronJobPortraitAlgorithmJob)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortraitAlgorithmJob.
func (in *PortraitAlgorithmJob) DeepCopy() *PortraitAlgorithmJob {
	if in == nil {
		return nil
	}
	out := new(PortraitAlgorithmJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortraitAlgorithmResultSource) DeepCopyInto(out *PortraitAlgorithmResultSource) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ConfigMapPortraitAlgorithmResultSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortraitAlgorithmResultSource.
func (in *PortraitAlgorithmResultSource) DeepCopy() *PortraitAlgorithmResultSource {
	if in == nil {
		return nil
	}
	out := new(PortraitAlgorithmResultSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortraitSpec) DeepCopyInto(out *PortraitSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Algorithm.DeepCopyInto(&out.Algorithm)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortraitSpec.
func (in *PortraitSpec) DeepCopy() *PortraitSpec {
	if in == nil {
		return nil
	}
	out := new(PortraitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaCron) DeepCopyInto(out *ReplicaCron) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaCron.
func (in *ReplicaCron) DeepCopy() *ReplicaCron {
	if in == nil {
		return nil
	}
	out := new(ReplicaCron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaProfile) DeepCopyInto(out *ReplicaProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaProfile.
func (in *ReplicaProfile) DeepCopy() *ReplicaProfile {
	if in == nil {
		return nil
	}
	out := new(ReplicaProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicaProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaProfileBehavior) DeepCopyInto(out *ReplicaProfileBehavior) {
	*out = *in
	in.PodSorter.DeepCopyInto(&out.PodSorter)
	in.PodTrafficController.DeepCopyInto(&out.PodTrafficController)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaProfileBehavior.
func (in *ReplicaProfileBehavior) DeepCopy() *ReplicaProfileBehavior {
	if in == nil {
		return nil
	}
	out := new(ReplicaProfileBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaProfileList) DeepCopyInto(out *ReplicaProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicaProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaProfileList.
func (in *ReplicaProfileList) DeepCopy() *ReplicaProfileList {
	if in == nil {
		return nil
	}
	out := new(ReplicaProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicaProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaProfileSpec) DeepCopyInto(out *ReplicaProfileSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	in.Behavior.DeepCopyInto(&out.Behavior)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaProfileSpec.
func (in *ReplicaProfileSpec) DeepCopy() *ReplicaProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicaProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaProfileStatus) DeepCopyInto(out *ReplicaProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaProfileStatus.
func (in *ReplicaProfileStatus) DeepCopy() *ReplicaProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaTimeSeriesPoint) DeepCopyInto(out *ReplicaTimeSeriesPoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaTimeSeriesPoint.
func (in *ReplicaTimeSeriesPoint) DeepCopy() *ReplicaTimeSeriesPoint {
	if in == nil {
		return nil
	}
	out := new(ReplicaTimeSeriesPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBehavior) DeepCopyInto(out *ScalingBehavior) {
	*out = *in
	if in.GrayStrategy != nil {
		in, out := &in.GrayStrategy, &out.GrayStrategy
		*out = new(GrayStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBehavior.
func (in *ScalingBehavior) DeepCopy() *ScalingBehavior {
	if in == nil {
		return nil
	}
	out := new(ScalingBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StabilityChecker) DeepCopyInto(out *StabilityChecker) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsStabilityChecker)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalStabilityChecker)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StabilityChecker.
func (in *StabilityChecker) DeepCopy() *StabilityChecker {
	if in == nil {
		return nil
	}
	out := new(StabilityChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticHorizontalPortraitData) DeepCopyInto(out *StaticHorizontalPortraitData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticHorizontalPortraitData.
func (in *StaticHorizontalPortraitData) DeepCopy() *StaticHorizontalPortraitData {
	if in == nil {
		return nil
	}
	out := new(StaticHorizontalPortraitData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticHorizontalPortraitProvider) DeepCopyInto(out *StaticHorizontalPortraitProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticHorizontalPortraitProvider.
func (in *StaticHorizontalPortraitProvider) DeepCopy() *StaticHorizontalPortraitProvider {
	if in == nil {
		return nil
	}
	out := new(StaticHorizontalPortraitProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesHorizontalPortraitData) DeepCopyInto(out *TimeSeriesHorizontalPortraitData) {
	*out = *in
	if in.TimeSeries != nil {
		in, out := &in.TimeSeries, &out.TimeSeries
		*out = make([]ReplicaTimeSeriesPoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesHorizontalPortraitData.
func (in *TimeSeriesHorizontalPortraitData) DeepCopy() *TimeSeriesHorizontalPortraitData {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesHorizontalPortraitData)
	in.DeepCopyInto(out)
	return out
}
