apiVersion: autoscaling.kapacity.traas.io/v1alpha1
kind: IntelligentHorizontalPodAutoscaler
metadata:
  name: cron-portrait-sample
spec:
  paused: false
  minReplicas: 0
  maxReplicas: 10
  portraitProviders:
    - type: Cron
      priority: 0
      cron:
        crons:
        - name: "cron-1"
          start: "0 * * * *"
          end: "10 * * * *"
          replicas: 1
        - name: "cron-2"
          start: "10 * * * *"
          end: "20 * * * *"
          replicas: 2
        - name: "cron-3"
          start: "20 * * * *"
          end: "30 * * * *"
          replicas: 3
        - name: "cron-4"
          start: "30 * * * *"
          end: "40 * * * *"
          replicas: 4
        - name: "cron-5"
          start: "40 * * * *"
          end: "50 * * * *"
          replicas: 5
  scaleTargetRef:
    kind: StatefulSet
    name: nginx
    apiVersion: apps/v1