apiVersion: autoscaling.kapacity.traas.io/v1alpha1
kind: IntelligentHorizontalPodAutoscaler
metadata:
  name: dynamic-portrait-reactive-sample
spec:
  paused: false
  minReplicas: 0
  maxReplicas: 10
  portraitProviders:
    - type: Dynamic
      priority: 0
      dynamic:
        portraitType: Reactive
        metrics:
          - name: metrics-scale-out
            type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 30
        algorithm:
          type: KubeHPA
  scaleTargetRef:
    kind: StatefulSet
    name: nginx
    apiVersion: apps/v1