apiVersion: autoscaling.kapacity.traas.io/v1alpha1
kind: IntelligentHorizontalPodAutoscaler
metadata:
  name: static-portrait-sample
spec:
  paused: false
  minReplicas: 0
  maxReplicas: 10
  portraitProviders:
    - type: Static
      priority: 0
      static:
        replicas: 2
  scaleTargetRef:
    kind: StatefulSet
    name: nginx
    apiVersion: apps/v1