# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import provider_pb2 as provider__pb2


class ProviderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryLatest = channel.unary_unary(
                '/io.kapacitystack.metric.ProviderService/QueryLatest',
                request_serializer=provider__pb2.QueryLatestRequest.SerializeToString,
                response_deserializer=provider__pb2.QueryLatestResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/io.kapacitystack.metric.ProviderService/Query',
                request_serializer=provider__pb2.QueryRequest.SerializeToString,
                response_deserializer=provider__pb2.QueryResponse.FromString,
                )


class ProviderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLatest,
                    request_deserializer=provider__pb2.QueryLatestRequest.FromString,
                    response_serializer=provider__pb2.QueryLatestResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=provider__pb2.QueryRequest.FromString,
                    response_serializer=provider__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io.kapacitystack.metric.ProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProviderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io.kapacitystack.metric.ProviderService/QueryLatest',
            provider__pb2.QueryLatestRequest.SerializeToString,
            provider__pb2.QueryLatestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io.kapacitystack.metric.ProviderService/Query',
            provider__pb2.QueryRequest.SerializeToString,
            provider__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
