# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import metric_pb2 as metric__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprovider.proto\x12\x17io.kapacitystack.metric\x1a\x0cmetric.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"C\n\x12QueryLatestRequest\x12-\n\x05query\x18\x01 \x01(\x0b\x32\x1e.io.kapacitystack.metric.Query\"G\n\x13QueryLatestResponse\x12\x30\n\x07samples\x18\x01 \x03(\x0b\x32\x1f.io.kapacitystack.metric.Sample\"\xba\x01\n\x0cQueryRequest\x12-\n\x05query\x18\x01 \x01(\x0b\x32\x1e.io.kapacitystack.metric.Query\x12)\n\x05start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x04step\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\"@\n\rQueryResponse\x12/\n\x06series\x18\x01 \x03(\x0b\x32\x1f.io.kapacitystack.metric.Series2\xd3\x01\n\x0fProviderService\x12h\n\x0bQueryLatest\x12+.io.kapacitystack.metric.QueryLatestRequest\x1a,.io.kapacitystack.metric.QueryLatestResponse\x12V\n\x05Query\x12%.io.kapacitystack.metric.QueryRequest\x1a&.io.kapacitystack.metric.QueryResponseB8Z6github.com/traas-stack/kapacity/pkg/metric/service/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'provider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/traas-stack/kapacity/pkg/metric/service/api'
  _globals['_QUERYLATESTREQUEST']._serialized_start=122
  _globals['_QUERYLATESTREQUEST']._serialized_end=189
  _globals['_QUERYLATESTRESPONSE']._serialized_start=191
  _globals['_QUERYLATESTRESPONSE']._serialized_end=262
  _globals['_QUERYREQUEST']._serialized_start=265
  _globals['_QUERYREQUEST']._serialized_end=451
  _globals['_QUERYRESPONSE']._serialized_start=453
  _globals['_QUERYRESPONSE']._serialized_end=517
  _globals['_PROVIDERSERVICE']._serialized_start=520
  _globals['_PROVIDERSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
